### PR TITLE
Test utils

### LINKED ISSUE #30: Improve from_hex()
- [ ] Make it case insensitive (support `A-F` chars).
- [ ] Throw exception on invalid input
- [ ] Add unit tests

### PR DESCRIPTION
**Pull request by chfast**
Closes #30

### CODE REVIEW

File: test/utils/utils.cpp [hunk 1]
```diff
@@ -10,6 +10,37 @@
 #include <iomanip>
 #include <iostream>
 
+bytes from_hex(std::string_view hex)
```
Comment (axic) [inline test/utils/utils.cpp]: Would it be an OK idea moving this to evmc so it can also be used in Hera?

Or perhaps creating yet another library? :D

Comment (chfast) [reply test/utils/utils.cpp]: Not sure... I'd rather copy&paste sources...
